const PLANTS = {
  hydrangea: {
    kind: "pretty",
    common: "Bigleaf Hydrangea",
    sci: "Hydrangea macrophylla",
    where: "East balcony · morning sun",
    art: { bloom: "hydrangeaBloom", rest: "hydrangeaRest" },
    bloomNote: "Summer: big round heads",
    restNote: "Winter: bare stems, fat buds",
    water: { big: "Thirsty", text: "Soak it whenever the top knuckle of soil is dry. Never let the pot dry out, even in winter.", signs: ["Droopy and the soil is dry? Give it a big soak.", "Droopy but the soil is wet? Leave it alone."] },
    sun: { big: "Morning sun, afternoon shade", text: "The east balcony suits it.", signs: ["Crispy brown leaf edges mean it got too dry or too much sun."] },
    soil: { mix: ["all-purpose soil", "a good handful of earthworm humus", "a small pour of perlite"], text: "It holds water without going soggy." },
    friends: "Shade lovers with shallow roots, like ferns, hostas, heuchera, impatiens or ivy trailing over the edge.",
    foes: "Dry-loving plants like lavender, rosemary, thyme, sage and succulents.",
    feed: { big: "Once a year.", text: "In spring, scratch a good handful of earthworm humus into the top of the soil. That's all it needs." },
    pruneArt: [["hydrangeaSnipSummer", "Summer"], ["hydrangeaSnipSpring", "Spring"]],
    pruneHow: "Clean snips just above a pair of fat buds. Never a hard chop: it flowers from last year's stems.",
    seasons: {
      spring: "Snip each old dried head down to the first fat buds. Cut out stems that are brown and dry all the way down, and lay the pieces on the soil to rot in.",
      summer: "When a flower fades, or for a vase, snip just above the first pair of full-size leaves below it. Stay high, the lower buds are next year's flowers.",
      fall: "No cutting. Next year's buds are already forming.",
      winter: "Leave the dried heads on. They shield the buds from frost and give tiny insects a place to spend the winter.",
    },
  },
  heather: {
    kind: "pretty",
    common: "Heather",
    sci: "Calluna vulgaris",
    where: "East balcony · morning sun",
    art: { bloom: "heatherBloom", rest: "heatherRest" },
    bloomNote: "Late summer to fall: spikes of tiny bells",
    restNote: "Evergreen, old flowers dry papery",
    water: { big: "Damp, never dry", text: "Tap water is fine. Keep the soil evenly damp, but never sitting in a puddle. Once it dries out completely it won't bounce back.", signs: ["Leaves yellowing? Scratch fresh ericaceous compost into the top, or add a small splash of vinegar to the watering can.", "Grey, brittle patches? It dried out. Water a little sooner next time."] },
    sun: { big: "As much as it can get", text: "More sun means more flowers, but the east balcony is fine.", signs: ["Leggy with few flowers? It wants more sun."] },
    soil: { mix: ["ericaceous compost", "a small pour of perlite"], text: "Nothing else. It needs acid soil." },
    friends: "Your other heather. Also other acid-soil lovers like small azaleas, blueberries, ferns or wintergreen.",
    foes: "The hydrangea, which hogs the water and shades it out. Also anything that wants regular, non-acid soil: lavender, rosemary, thyme, most vegetables, succulents and bromeliads.",
    feed: { big: "No.", text: "It likes poor soil, and feeding makes it floppy. Just scratch fresh ericaceous compost into the top each spring to keep the soil acid." },
    pruneArt: [["heatherSnipSpring", "Spring"]],
    pruneHow: "A light haircut with scissors, just below the faded flowers. Never cut into bare brown wood, because it won't regrow from there.",
    seasons: {
      spring: "Trim off last year's faded flower spikes, staying in the green leafy part. Let the clippings fall on the soil.",
      summer: "Leave it. The flower buds are forming.",
      fall: "Leave it to flower. Late bees and hoverflies feed on it when little else is blooming.",
      winter: "Leave the papery old flowers on for color.",
    },
  },
  urnplant: {
    kind: "pretty",
    common: "Urn Plant",
    sci: "Aechmea fasciata",
    where: "East balcony · morning sun",
    art: { bloom: "urnBloom", rest: "urnRest" },
    bloomNote: "Flowers once: a spiky pink head",
    restNote: "After flowering: mom fades, babies grow",
    water: { big: "Soak, then let it dry", text: "Pour over the whole plant so the cup fills and the soil soaks until water runs out the bottom. Let the soil go nearly dry before the next soak. Tap water is fine.", signs: ["Every few weeks, tip the cup out and refill it so the water doesn't go stale."] },
    sun: { big: "Bright, gentle light", text: "Morning sun is perfect, so the east balcony suits it.", signs: ["Pale, bleached patches mean too much sun."] },
    soil: { mix: ["succulent soil", "a good pour of perlite"], text: "Use a small pot. The roots mostly just hold it in place." },
    friends: "Its own babies, the flaming sword or other bromeliads. Also air plants tucked on top, or small succulents that like the same dry mix.",
    foes: "Anything that likes wet or rich soil, like the hydrangea, heather, ferns, vegetables and most herbs. Their roots would rot.",
    feed: { big: "No.", text: "It doesn't need it." },
    pruneArt: [["urnSnipMom", "Spring"]],
    pruneHow: "Clean scissors, cut close to the base. Each rosette flowers once, then the mom slowly fades and her babies take over.",
    seasons: {
      spring: "Do the bigger cuts. Once mom is mostly brown, cut her off at the base and leave the babies. Keep them as a clump, or cut one off with some root once it's about a third of mom's size and pot it alone.",
      summer: "Leave dry, brown leaves on unless they bother you. Small bugs hide in them.",
      fall: "Cut the old flower stalk off at the base once it's dry.",
      winter: "Leave it alone.",
    },
  },
  inchplant: {
    kind: "pretty",
    common: "Inch Plant",
    sci: "Tradescantia zebrina",
    where: "East balcony · morning sun",
    art: { bloom: "inchBloom", rest: "inchRest" },
    bloomNote: "Small three-petal pink flowers at the tips",
    restNote: "Silver-striped leaves all year",
    water: { big: "Let the top dry, then soak", text: "Soak it when the top knuckle of soil is dry. It handles going dry much better than staying wet.", signs: ["Mushy stems at the base? It's too wet. Let it dry out longer."] },
    sun: { big: "Bright, gentle light", text: "Morning sun is right, so the east balcony suits it. Harsh afternoon sun bleaches the stripes.", signs: ["Stripes fading and stems stretching? It needs more light.", "Crispy brown leaves? Too much sun, or it went too dry."] },
    soil: { mix: ["all-purpose soil", "a small pour of perlite"], text: "Nothing fancy." },
    friends: "The spider plant or pothos, or other easy trailers like purple heart, string of hearts or creeping Jenny. They like the same watering.",
    foes: "Anything that likes soggy or acid soil, like the hydrangea, heather or ferns. Also succulents and cacti, which want it much drier.",
    feed: { big: "No.", text: "It already grows well." },
    pruneArt: [["inchSnip", "Any time"]],
    pruneHow: "Snip just above a leaf joint and it branches into two right there, getting bushier. Every cutting roots in a glass of water.",
    seasons: {
      spring: "Cut leggy stems back by half. Anything the frost killed can stay on the soil to rot in, since it regrows from the roots.",
      summer: "Pinch off long tips to keep it full.",
      fall: "Trim stems that flop over.",
      winter: "Leave it alone.",
    },
  },
  spiderplant: {
    kind: "pretty",
    common: "Spider Plant",
    sci: "Chlorophytum comosum",
    where: "East balcony · morning sun",
    art: { bloom: "spiderBloom", rest: "spiderRest" },
    bloomNote: "Little white stars on long runners",
    restNote: "Babies dangle from the runners",
    water: { big: "Let the top dry, then soak", text: "Soak it when the top knuckle of soil is dry. Its thick roots store water, so it forgives forgetting." },
    sun: { big: "Bright, gentle light", text: "Morning sun is right, so the east balcony suits it." },
    soil: { mix: ["all-purpose soil", "a small pour of perlite"], text: "Nothing fancy." },
    friends: "The inch plant or pothos, or other easy leafy plants like peace lily, prayer plant, ferns or ivy.",
    foes: "Anything that likes soggy or acid soil, like the hydrangea, heather or ferns. Also succulents and cacti, which want it much drier.",
    feed: { big: "No.", text: "It doesn't need it." },
    pruneArt: [["spiderSnip", "Any time"]],
    pruneHow: "Cut whole leaves off at the base, never halfway. The babies hang off long runners: snip a runner near mom to pot a baby, or just leave them dangling.",
    seasons: {
      spring: "Cut brown or frost-hit leaves off at the base and leave them on the soil. Pot any babies you want.",
      summer: "Trim runners only if mom's center looks pale or thin, or they're in your way.",
      fall: "Leave it alone.",
      winter: "Leave it alone.",
    },
  },
  pothos: {
    kind: "pretty",
    common: "Pothos",
    sci: "Epipremnum aureum",
    where: "East balcony · morning sun",
    art: { bloom: "pothosVine" },
    bloomTitle: "What it looks like",
    bloomNote: "Trailing vines; it almost never flowers in a pot",
    water: { big: "Let it dry a bit, then soak", text: "Soak it when the top two knuckles of soil are dry. It droops a little when thirsty and perks right back up." },
    sun: { big: "Bright, gentle light", text: "The east balcony is fine. Harsh sun yellows the leaves." },
    soil: { mix: ["all-purpose soil", "a small pour of perlite"], text: "Nothing fancy." },
    friends: "The Swiss cheese vine, spider plant or inch plant. Also philodendron, peace lily or ivy.",
    foes: "Anything that likes soggy or acid soil, like the hydrangea, heather or ferns. Also succulents and cacti, which want it much drier.",
    feed: { big: "No.", text: "It doesn't need it." },
    pruneArt: [["pothosSnip", "Spring"]],
    pruneHow: "Snip just above a leaf joint, where the little brown root bump is. Cuttings root in water, or poke them straight back into the same pot to make it fuller.",
    seasons: {
      spring: "Cut leggy vines back by a third. Leave frost-hit leaves on the soil to rot in.",
      summer: "Trim vines that get too long.",
      fall: "Leave it alone.",
      winter: "Leave it alone.",
    },
  },
  tomato: {
    kind: "food",
    common: "Tomato",
    sci: "Solanum lycopersicum",
    where: "West balcony · full sun",
    art: { bloom: "tomatoBloom", rest: "tomatoYoung" },
    bloomNote: "Yellow star flowers, then fruit",
    restTitle: "Young plant",
    restNote: "Spring: fuzzy, toothed leaves",
    water: { big: "Thirsty, and steady", text: "Give it a deep soak whenever the top knuckle is dry. In summer heat that can be daily. Swinging between bone dry and soaked cracks the fruit." },
    sun: { big: "As much as it can get", text: "The west balcony is right." },
    soil: { mix: ["vegetable soil", "a good handful of earthworm humus"], text: "In a big pot, like your 50L." },
    friends: "The basil, green onions and pepper already in its pot. Also chives, parsley, marigolds, nasturtiums, borage or lettuce at its feet.",
    foes: "Big, hungry plants like the cannabis, corn, squash or pumpkins. Potatoes and eggplant, which share its diseases. Fennel, which slows its growth. Cabbage-family plants like broccoli and cauliflower.",
    feed: { big: "Twice.", text: "A handful of earthworm humus at planting, and another when the first little tomatoes appear. Optional boost: half the label dose of the liquid feed in the watering can every couple of weeks while fruit is forming." },
    pruneArt: [["tomatoSnip", "Fall"]],
    pruneHow: "Let it grow however it wants. The only cut is at the end of the season.",
    seasons: {
      spring: "Nothing to cut.",
      summer: "Nothing to cut.",
      fall: "Once it stops fruiting, cut it at soil level and leave the roots in the pot to feed the soil.",
      winter: "Nothing. It only lives one season.",
    },
  },
  basil: {
    kind: "food",
    common: "Basil",
    sci: "Ocimum basilicum",
    where: "West balcony · full sun",
    art: { bloom: "basilBloom", rest: "basilLeafy" },
    bloomNote: "Spikes of small white flowers",
    restTitle: "Leafy",
    restNote: "Soft, glossy, rounded leaves in pairs",
    water: { big: "Watered with its pot-mates", text: "It wilts fast when dry and bounces back after a soak." },
    sun: { big: "Full sun", text: "The west balcony is right." },
    soil: { mix: ["whatever its pot has"], text: "It's happy in the tomato's vegetable soil and humus." },
    friends: "The tomato, peppers, green onions, cannabis and ginger. Also parsley, chives, marigolds, nasturtiums or lettuce.",
    foes: "Rosemary, lavender, thyme or sage, which want it much drier. Also fennel.",
    feed: { big: "No.", text: "It feeds off what the tomato gets." },
    pruneArt: [["basilSnip", "Summer"]],
    pruneHow: "Nothing beyond picking it to eat. Pinch from the top, just above a pair of leaves, and it bushes out. Let it flower, because hoverflies and bees love basil flowers.",
    seasons: {
      spring: "Nothing to cut.",
      summer: "Pick from the top to eat. Let some stems flower.",
      fall: "Leave the flower spikes on until they turn brown and dry. Then snip them and rub them over a bowl to collect the small black seeds.",
      winter: "Nothing. It only lives one season.",
    },
  },
  flamingsword: {
    kind: "pretty",
    common: "Flaming Sword",
    sci: "Vriesea",
    where: "East balcony · morning sun",
    art: { bloom: "swordBloom", rest: "swordRest" },
    bloomNote: "Flowers once: a flat yellow sword",
    restNote: "After flowering: mom fades, babies grow",
    water: { big: "Soak, then let it dry", text: "Pour over the whole plant so the cup fills and the soil soaks through. Let the soil go nearly dry before the next soak. Refresh the cup every few weeks." },
    sun: { big: "Soft morning light", text: "Its thinner leaves scorch in hot sun, so the east balcony is right." },
    soil: { mix: ["succulent soil", "a good pour of perlite"], text: "Use a small pot." },
    friends: "Its own babies or the urn plant, or other bromeliads. Also air plants tucked on top, or small succulents that like the same dry mix.",
    foes: "Anything that likes wet or rich soil, like the hydrangea, heather, ferns, vegetables and most herbs. Their roots would rot.",
    feed: { big: "No.", text: "It doesn't need it." },
    pruneArt: [["urnSnipMom", "Spring"]],
    pruneHow: "Clean scissors, cut close to the base. Each rosette flowers once, then the mom slowly fades and her babies take over.",
    seasons: {
      spring: "Once mom is mostly brown, cut her off at the base and leave the babies.",
      summer: "Nothing to cut.",
      fall: "Cut the old flower stalk off at the base once it's dry.",
      winter: "Nothing to cut.",
    },
  },
  pepper: {
    kind: "food",
    common: "Pepper",
    sci: "Capsicum annuum",
    where: "West balcony · full sun",
    art: { bloom: "pepperBloom", rest: "pepperSeedling" },
    bloomNote: "Small white flowers, then hanging peppers",
    restTitle: "Seedling",
    restNote: "Two seed leaves, then pointed true leaves",
    water: { big: "Let the top dry, then soak", text: "Soak it when the top knuckle is dry. It likes it a touch drier than the tomato." },
    sun: { big: "Full sun and warmth", text: "The west balcony is right." },
    soil: { mix: ["vegetable soil", "a good handful of earthworm humus"], text: "Seedlings coming up this late may sit still until spring. That's normal." },
    friends: "The tomato, basil and green onions. Also chives, parsley, marigolds, nasturtiums or carrots.",
    foes: "Big, hungry plants like the cannabis, corn or squash. Potatoes and eggplant, which share its diseases. Also fennel.",
    feed: { big: "Once.", text: "Scratch a handful of earthworm humus in when the first flowers show. Optional boost: half the label dose of the liquid feed in the watering can every couple of weeks while peppers are forming." },
    pruneArt: [["pepperSnip", "Summer"]],
    pruneHow: "No pruning. Pick peppers whenever they're the color you like, snipping rather than pulling so the branch doesn't snap.",
    seasons: {
      spring: "If it made it through winter, snip off any dead stems.",
      summer: "Pick peppers whenever they're the color you like.",
      fall: "Keep picking. Leave the plant outside, since peppers can live more than one year where winters are mild.",
      winter: "Nothing to cut.",
    },
  },
  strawberry: {
    kind: "food",
    common: "Strawberry",
    sci: "Fragaria × ananassa",
    where: "West balcony · full sun",
    art: { bloom: "strawBloom", rest: "strawLeafy" },
    bloomNote: "White flowers, then berries",
    restTitle: "Leafy, with runners",
    restNote: "Leaves in threes; runners make baby plants",
    water: { big: "Let the top dry, then soak", text: "Soak it when the top knuckle is dry. The roots are shallow and the pot is wide and shallow, so it dries fast in summer." },
    sun: { big: "Full sun", text: "More sun means more berries, so the west balcony is right." },
    soil: { mix: ["vegetable soil", "a good handful of earthworm humus", "a small pour of perlite"], text: "It comes back every year in the same pot." },
    friends: "The green onions and chives already there, whose smell helps keep pests off. Also thyme, borage, lettuce or marigolds.",
    foes: "The tomato, peppers, potatoes or eggplant, which share a wilt disease. Cabbage-family plants like broccoli and cauliflower.",
    feed: { big: "Once a year.", text: "Scratch a handful of earthworm humus in each spring. Optional boost: half the label dose of the liquid feed in the watering can every couple of weeks while berries are forming." },
    pruneArt: [["strawSnip", "Any time"]],
    pruneHow: "Let the runners root and fill the pot. Snip them only once the pot is full.",
    seasons: {
      spring: "Leave dead brown leaves where they fall. They rot into the soil like a forest floor.",
      summer: "Let runners root. Snip them only if the pot is full.",
      fall: "Nothing to cut.",
      winter: "Nothing to cut.",
    },
  },
  greenonion: {
    kind: "food",
    common: "Green Onion",
    sci: "Allium fistulosum",
    where: "West balcony · full sun",
    art: { bloom: "onionBloom", rest: "onionLeafy" },
    bloomNote: "Round balls of tiny cream flowers",
    restTitle: "Leafy",
    restNote: "Hollow tube leaves from slim white bases",
    water: { big: "Nothing extra", text: "It drinks from whichever pot it's in. When you water the tomato or strawberry, it gets its share." },
    sun: { big: "Full sun", text: "Full sun is fine, and it copes with some shade too." },
    soil: { mix: ["whatever the pot already has"], text: "It's happy in the tomato's and strawberry's vegetable soil." },
    friends: "Tomato, strawberry, pepper and basil, whose pests its smell helps keep off. Also carrots, lettuce, beets, parsley or chamomile.",
    foes: "Beans and peas, since onions slow their growth. Also asparagus.",
    feed: { big: "No.", text: "It feeds off what its pot-mates get." },
    pruneArt: [["onionSnip", "Any time"]],
    pruneHow: "Cut what you need a finger's width above the soil and it regrows from the base. If one flowers, leave the flower ball on for the hoverflies and bees.",
    seasons: {
      spring: "Cut what you want to eat.",
      summer: "Leave any flower balls on for the hoverflies and bees.",
      fall: "Cut what you want to eat.",
      winter: "Leave it alone. It may die back and return in spring.",
    },
  },
  monstera: {
    kind: "pretty",
    common: "Swiss Cheese Vine",
    sci: "Monstera adansonii",
    where: "East balcony · morning sun",
    art: { bloom: "monsteraVine" },
    bloomTitle: "What it looks like",
    bloomNote: "Vines of holey leaves; it almost never flowers in a pot",
    water: { big: "Let the top dry, then soak", text: "Soak it when the top knuckle of soil is dry." },
    sun: { big: "Morning sun, then shade", text: "The east balcony suits it." },
    soil: { mix: ["all-purpose soil", "a good pour of perlite"], text: "Airy, so the roots get air." },
    friends: "The pothos, which likes the same care. Also philodendron, peace lily or ivy.",
    foes: "Anything that likes soggy or acid soil, like the hydrangea, heather or ferns. Also succulents and cacti, which want it much drier.",
    feed: { big: "Once a year.", text: "In spring, scratch a handful of earthworm humus into the top of the soil." },
    pruneArt: [["monsteraSnip", "Any time"]],
    pruneHow: "Snip just above a leaf joint, where the thin brown air root is, whenever it gets too long. Cuttings root in water, or poke them straight back into the same pot.",
    seasons: {
      spring: "Cut off leaves the cold turned brown and leave them on the soil to rot in.",
      summer: "Snip vines that get too long.",
      fall: "Leave it alone.",
      winter: "Leave it alone.",
    },
  },
  ginger: {
    kind: "food",
    common: "Ginger",
    sci: "Zingiber officinale",
    where: "East balcony · morning sun",
    art: { bloom: "gingerPlant" },
    bloomTitle: "What it looks like",
    bloomNote: "Leafy stalks from a knobbly root; it rarely flowers in a pot",
    water: { big: "Lightly moist in summer", text: "Keep it lightly moist while it's leafy. Once the leaves yellow in fall, barely water it until spring." },
    sun: { big: "Morning sun, then shade", text: "The east balcony suits it." },
    soil: { mix: ["all-purpose soil", "a good handful of earthworm humus", "a small pour of perlite"], text: "A shallow, wide pot is ideal, since the root spreads sideways." },
    friends: "The two basil plants already there. Also turmeric, lemongrass, parsley or cilantro, which like the same moist, rich soil.",
    foes: "Rosemary, lavender, thyme, sage and succulents, which want it much drier.",
    feed: { big: "Once a year.", text: "In spring, scratch a handful of earthworm humus into the top of the soil." },
    pruneArt: [["gingerSnip", "Harvest"]],
    pruneHow: "No pruning. To harvest, break off a piece of root at the pot's edge and leave the rest to keep growing.",
    seasons: {
      spring: "Nothing to cut. New shoots come up from the root.",
      summer: "Nothing to cut.",
      fall: "Harvest a piece if you like. When the leaves die back, leave them on the soil.",
      winter: "Leave it alone and keep it on the dry side.",
    },
  },
  lavender: {
    kind: "pretty",
    common: "Lavender",
    sci: "Lavandula",
    where: "West balcony · full sun",
    art: { bloom: "lavenderBloom", rest: "lavenderRest" },
    bloomNote: "Purple spikes the bees love",
    restTitle: "Out of bloom",
    restNote: "A grey-green mound",
    water: { big: "Let it dry out, then soak", text: "Let the pot dry out completely, then soak it. It hates wet feet." },
    sun: { big: "Full sun", text: "The more sun the better, so the west balcony is right." },
    soil: { mix: ["succulent soil", "a good pour of perlite"], text: "It likes lean soil, and the lime in your tap water actually suits it." },
    friends: "Rosemary once your cuttings root, thyme, sage or oregano. Also small succulents like sedum, which like it just as dry.",
    foes: "Thirsty or acid-soil plants like basil, tomato, strawberry, hydrangea, heather or ferns.",
    feed: { big: "No.", text: "Rich soil makes it floppy." },
    pruneArt: [["lavenderSnip", "Late summer"]],
    pruneHow: "Once the bees are done with the flowers in late summer, cut off the old flower stalks plus a little of the leaves, about a third of the plant. Stay in the green leafy part, never into the woody grey stem, because it won't regrow from there.",
    seasons: {
      spring: "Nothing to cut.",
      summer: "Leave the flowers for the bees. Once they fade, cut back by a third and let the clippings fall on the soil.",
      fall: "Nothing to cut.",
      winter: "Leave it alone and keep it on the dry side.",
    },
  },
  starjasmine: {
    kind: "pretty",
    common: "Star Jasmine",
    sci: "Trachelospermum jasminoides",
    where: "West balcony · full sun",
    art: { bloom: "jasmineBloom", rest: "jasmineRest" },
    bloomNote: "White pinwheels; the scent peaks in the evening and draws moths and bees",
    restTitle: "Out of bloom",
    restNote: "Glossy and green all year",
    water: { big: "Let the top dry, then soak", text: "Soak it when the top knuckle is dry. Water less in winter." },
    sun: { big: "Full sun", text: "The west balcony is fine, and it also takes some shade." },
    soil: { mix: ["all-purpose soil", "a good handful of earthworm humus", "a small pour of perlite"], text: "It stays in the same pot for years." },
    friends: "Low, shallow plants at its feet, like sweet alyssum, nasturtiums, creeping Jenny, or spring bulbs such as crocus and grape hyacinth.",
    foes: "Other strong climbers like the morning glory, which smother each other. Big, hungry plants like cannabis or tomato. Heather, which needs acid soil.",
    feed: { big: "Once a year.", text: "In spring, scratch a handful of earthworm humus into the top of the soil." },
    pruneArt: [["jasmineSnip", "Summer"]],
    pruneHow: "None needed. Right after it flowers, snip stray shoots back to a leaf pair only if they're in the way, and let the clippings fall on the soil. The milky sap is sticky, so wash your hands after.",
    seasons: {
      spring: "Nothing to cut.",
      summer: "Leave the flowers for the moths and bees. Afterward, snip stray shoots only if they're in the way.",
      fall: "Nothing to cut.",
      winter: "Leave it alone.",
    },
  },
  morningglory: {
    kind: "pretty",
    common: "Morning Glory",
    sci: "Ipomoea",
    where: "West balcony · full sun",
    art: { bloom: "mgBloom", rest: "mgRest" },
    bloomNote: "Trumpets that open each morning",
    restTitle: "Climbing",
    restNote: "Heart-shaped leaves twining up",
    water: { big: "Let the top dry, then soak", text: "Soak it when the top knuckle is dry." },
    sun: { big: "Full sun", text: "More sun, more flowers." },
    soil: { mix: ["all-purpose soil", "a small pour of perlite"], text: "Lean soil means more flowers." },
    friends: "Low plants at its feet, like nasturtiums, sweet alyssum or marigolds.",
    foes: "The star jasmine or other climbers, which it smothers. Also tomato, peppers or heather.",
    feed: { big: "No.", text: "Rich soil gives leaves instead of flowers." },
    pruneArt: [["mgWait", "This winter"]],
    pruneHow: "No pruning. Leave it standing this winter as bug shelter. If it sprouts from the base in spring, it's the perennial blue dawn flower (Ipomoea indica). If nothing comes back, it was the annual (Ipomoea purpurea): pull the dead vine then, and keep any seedlings. The seeds aren't edible.",
    seasons: {
      spring: "Watch the base. New shoots mean perennial; nothing means annual, so pull the dead vine.",
      summer: "Nothing to cut. Let it climb.",
      fall: "Leave seed pods to dry on the vine so it can reseed.",
      winter: "Leave it standing. Bugs shelter in it.",
    },
  },
  succulents: {
    kind: "pretty",
    common: "Succulent Box",
    sci: "Aeonium, Crassula, Graptopetalum, Gasteria, Haworthia",
    where: "East balcony · morning sun",
    art: { bloom: "succBox" },
    bloomTitle: "Who lives here",
    bloomNote: "Aeonium, pine tree crassula, ghost plant, ox tongue, zebra plant, plus one stretched rosette still to name",
    water: { big: "Let it dry out, then soak", text: "Let the soil dry out completely, then soak. In winter, barely water." },
    sun: { big: "Morning sun", text: "The east balcony is fine. A plant stretching tall is asking for more light." },
    soil: { mix: ["succulent soil", "a good pour of perlite"], text: "What's in the box now is right." },
    friends: "Each other, plus the bromeliads, houseleeks, sedums or small cacti.",
    foes: "Thirsty plants like the hydrangea, heather, ferns, basil, tomato or strawberry.",
    feed: { big: "No.", text: "They don't need it." },
    pruneArt: [["succSnip", "Any time"]],
    pruneHow: "No pruning. Let fallen leaves and broken bits root where they land, the way they spread in the wild.",
    seasons: {
      spring: "Nothing to cut.",
      summer: "Leave flower stalks for the bees until they dry. An aeonium rosette dies after it flowers; its side shoots carry on.",
      fall: "Snip dry flower stalks off at the base.",
      winter: "Barely water. Leave them alone.",
    },
  },
};
